// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI tool to analyze an issue from a photo and user feedback.
 *
 * - analyzeIssue - A function that analyzes a photo to generate issue details.
 * - AnalyzeIssueInput - The input type for the analyzeIssue function.
 * - AnalyzeIssueOutput - The return type for the analyzeIssue function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeIssueInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a civic issue, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  userFrustration: z.number().min(1).max(5).optional(),
  userUrgency: z.number().min(1).max(5).optional(),
  peopleAffected: z.string().optional(),
  duration: z.string().optional(),
  userFeedback: z.string().optional(),
});
export type AnalyzeIssueInput = z.infer<typeof AnalyzeIssueInputSchema>;

const AnalyzeIssueOutputSchema = z.object({
  title: z
    .string()
    .describe('A concise, descriptive title for the issue (e.g., "Overflowing Garbage Bin").'),
  description: z
    .string()
    .describe('A detailed, well-written description of the issue based on the photo and user feedback, written from the user\'s perspective.'),
  category: z
    .enum(['Water', 'Electricity', 'Roads', 'Waste', 'Other'])
    .describe('The most relevant category for the issue.'),
  summary: z
    .string()
    .describe('A 1-2 line summary of the description, suitable for a feed view.'),
});
export type AnalyzeIssueOutput = z.infer<typeof AnalyzeIssueOutputSchema>;

export async function analyzeIssue(
  input: AnalyzeIssueInput
): Promise<AnalyzeIssueOutput> {
  return analyzeIssueFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeIssuePrompt',
  input: {schema: AnalyzeIssueInputSchema},
  output: {schema: AnalyzeIssueOutputSchema},
  prompt: `You are a helpful assistant for a civic issue reporting app. Your goal is to help a citizen write a compelling issue report.

Analyze the following image and the user's feedback. Based on ALL of this information, please provide the following in JSON format:

1.  **title**: A short, clear title for the issue.
2.  **description**: A detailed description of the problem. **IMPORTANT**: Write this from the user's point of view. Use the user's feedback to capture their tone and perspective. For example, if they are frustrated, the description should reflect that.
3.  **category**: Classify the issue into one of these categories: 'Water', 'Electricity', 'Roads', 'Waste', 'Other'.
4.  **summary**: A concise, 1-2 line summary of the detailed description.

**Image to analyze:** 
{{media url=photoDataUri}}

**User's Feedback:**
- Frustration Level: {{{userFrustration}}}/5
- Urgency Level: {{{userUrgency}}}/5
- People Affected: {{{peopleAffected}}}
- Issue Duration: {{{duration}}}
- Additional Comments: "{{{userFeedback}}}"

Now, generate the report details based on the image and the user's feedback.
`,
});

const analyzeIssueFlow = ai.defineFlow(
  {
    name: 'analyzeIssueFlow',
    inputSchema: AnalyzeIssueInputSchema,
    outputSchema: AnalyzeIssueOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
