// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI tool to analyze a spoken issue description and/or image to generate a report.
 *
 * - analyzeIssue - A function that analyzes spoken text to generate issue details.
 * - AnalyzeIssueInput - The input type for the analyzeIssue function.
 * - AnalyzeIssueOutput - The return type for the analyzeIssue function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeIssueInputSchema = z.object({
  spokenDescription: z
    .string()
    .optional()
    .describe('The full, transcribed text of what the user said about the civic issue.'),
  photoDataUri: z
    .string()
    .optional()
    .describe(
      "A photo of the issue, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  language: z.string().describe("The language of the user's spoken description (e.g., 'en', 'hi')."),
});
export type AnalyzeIssueInput = z.infer<typeof AnalyzeIssueInputSchema>;

const AnalyzeIssueOutputSchema = z.object({
  title: z
    .string()
    .describe('A concise, descriptive title for the issue based on the spoken text (e.g., "Overflowing Garbage Bin Outside College").'),
  description: z
    .string()
    .describe('A detailed, well-written description of the issue based on the spoken text. This should be a cleaned-up and elaborated version of what the user said.'),
  category: z
    .enum(['Water', 'Electricity', 'Roads', 'Waste', 'Other'])
    .describe('The most relevant category for the issue.'),
  summary: z
    .string()
    .describe('A 1-2 line summary of the description, suitable for a feed view.'),
});
export type AnalyzeIssueOutput = z.infer<typeof AnalyzeIssueOutputSchema>;

export async function analyzeIssue(
  input: AnalyzeIssueInput
): Promise<AnalyzeIssueOutput> {
  return analyzeIssueFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeIssuePrompt',
  input: {schema: AnalyzeIssueInputSchema},
  output: {schema: AnalyzeIssueOutputSchema},
  prompt: `You are a helpful assistant for a civic issue reporting app. Your goal is to take a user's spoken complaint and/or an image and convert it into a well-structured report.

Analyze the user's input below. The photo is the primary source of truth if provided. Use the spoken description for additional context if it exists. Based on this information, please provide the following in JSON format:

1.  **title**: A short, clear title for the issue.
2.  **description**: A detailed description of the problem. If there was spoken text, rephrase it to be a clear and formal complaint. If there was only a photo, describe the scene in the photo.
3.  **category**: Classify the issue into one of these categories: 'Water', 'Electricity', 'Roads', 'Waste', 'Other'.
4.  **summary**: A concise, 1-2 line summary of the detailed description.

**IMPORTANT**: Your response for the title, description, and summary fields MUST be in the same language as the user's input, which is provided as language code '{{language}}'. Do not translate the user's input.

**User's Spoken Description (optional):**
"{{{spokenDescription}}}"

**User's Photo (optional):**
{{#if photoDataUri}}
  {{media url=photoDataUri}}
{{/if}}

Now, generate the report details based on the user's input.
`,
});

const analyzeIssueFlow = ai.defineFlow(
  {
    name: 'analyzeIssueFlow',
    inputSchema: AnalyzeIssueInputSchema,
    outputSchema: AnalyzeIssueOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
