
// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI tool to calculate an urgency score for a civic issue.
 *
 * - calculateUrgencyScore - A function that calculates the urgency score.
 * - CalculateUrgencyScoreInput - The input type for the calculateUrgencyScore function.
 * - CalculateUrgencyScoreOutput - The return type for the calculateUrgencyScore function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CalculateUrgencyScoreInputSchema = z.object({
  description: z.string().describe('The description of the issue.'),
  photosDataUri: z
    .array(z.string())
    .describe(
      "An array of photos of the issue, as data URIs that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  upvotes: z.number().describe('The number of upvotes for the issue.'),
  downvotes: z.number().describe('The number of downvotes for the issue.'),
  userFrustration: z
    .number()
    .min(1)
    .max(5)
    .describe('User-reported frustration level (1-5 stars).'),
  userUrgency: z
    .number()
    .min(1)
    .max(5)
    .describe('User-reported urgency level (1-5 stars).'),
  peopleAffected: z.string().optional().describe("Scale of people affected (e.g., 'A whole community')"),
  duration: z.string().optional().describe("How long the issue has persisted (e.g., 'More than a month')"),
  userFeedback: z.string().optional().describe('Optional additional feedback from the user.'),
});
export type CalculateUrgencyScoreInput = z.infer<
  typeof CalculateUrgencyScoreInputSchema
>;

const CalculateUrgencyScoreOutputSchema = z.object({
  urgencyScore: z
    .number()
    .describe(
      'The calculated urgency score, out of 100. Based on description sentiment (20 pts), image analysis (40 pts), votes (20 pts), and user sentiment (20 pts).'
    ),
  reason: z
    .string()
    .describe('A brief explanation of how the score was calculated.'),
});
export type CalculateUrgencyScoreOutput = z.infer<
  typeof CalculateUrgencyScoreOutputSchema
>;

export async function calculateUrgencyScore(
  input: CalculateUrgencyScoreInput
): Promise<CalculateUrgencyScoreOutput> {
  return calculateUrgencyScoreFlow(input);
}

const prompt = ai.definePrompt({
  name: 'calculateUrgencyScorePrompt',
  input: {schema: CalculateUrgencyScoreInputSchema},
  output: {schema: CalculateUrgencyScoreOutputSchema},
  prompt: `You are an AI assistant that calculates an urgency score for a civic issue. The total score is out of 100.

The scoring is weighted as follows:
1.  **Image Analysis (40 points):** Analyze the provided images. Issues that appear dangerous, widespread, or environmentally damaging (e.g., large potholes, exposed wires, major leaks) get a higher score. Minor issues (e.g., small cracks, single overflowing bin) get a lower score. If no images are provided, this score is 0.
2.  **User Sentiment & Context (30 points):** Based on the user's rated frustration ({{{userFrustration}}}/5), urgency ({{{userUrgency}}}/5), the number of people affected ({{{peopleAffected}}}), and the duration of the problem ({{{duration}}}). Widespread, long-lasting, and frustrating issues get a higher score.
3.  **Community Votes (15 points):** The score is the number of upvotes minus downvotes. 20+ net upvotes = 15 points. Negative net votes result in 0 points for this category. (Upvotes: {{{upvotes}}}, Downvotes: {{{downvotes}}})
4.  **Description & Feedback Analysis (15 points):** Analyze the text description and user feedback for sentiment. A more negative, urgent, or distressed tone gets a higher score.

Combine these to calculate a final score out of 100. Provide a brief reason for your calculation.

**Input:**
Description: {{{description}}}
User Feedback: {{{userFeedback}}}
Photos:
{{#each photosDataUri}}
- {{media url=this}}
{{/each}}

Analyze the provided information and return the urgency score and reason in the specified JSON format.`,
});

const calculateUrgencyScoreFlow = ai.defineFlow(
  {
    name: 'calculateUrgencyScoreFlow',
    inputSchema: CalculateUrgencyScoreInputSchema,
    outputSchema: CalculateUrgencyScoreOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
