// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI tool to filter false complaints based on image analysis and historical data.
 *
 * - filterFalseComplaints - A function that filters false complaints.
 * - FilterFalseComplaintsInput - The input type for the filterFalseComplaints function.
 * - FilterFalseComplaintsOutput - The return type for the filterFalseComplaints function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FilterFalseComplaintsInputSchema = z.object({
  photosDataUri: z
    .array(z.string())
    .describe(
      "An array of photos of the issue, as data URIs that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  description: z.string().describe('The description of the issue.'),
  historicalData: z
    .string()
    .describe('Historical data related to similar complaints.'),
});
export type FilterFalseComplaintsInput = z.infer<
  typeof FilterFalseComplaintsInputSchema
>;

const FilterFalseComplaintsOutputSchema = z.object({
  isValidComplaint: z
    .boolean()
    .describe('Whether the complaint is valid or not.'),
  reason: z.string().describe('The reason for the complaint being invalid.'),
});
export type FilterFalseComplaintsOutput = z.infer<
  typeof FilterFalseComplaintsOutputSchema
>;

export async function filterFalseComplaints(
  input: FilterFalseComplaintsInput
): Promise<FilterFalseComplaintsOutput> {
  return filterFalseComplaintsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'filterFalseComplaintsPrompt',
  input: {schema: FilterFalseComplaintsInputSchema},
  output: {schema: FilterFalseComplaintsOutputSchema},
  prompt: `You are an AI tool that filters out false complaints based on image analysis and historical data.

You will use the provided information to determine if the complaint is valid or not.

Description: {{{description}}}
Photos:
{{#each photosDataUri}}
- {{media url=this}}
{{/each}}
Historical Data: {{{historicalData}}}

Based on the images, description and historical data, determine if the complaint is valid and provide a reason for your determination.

Output in JSON format:
{
  "isValidComplaint": true/false,
  "reason": "reason for the determination"
}
`,
});

const filterFalseComplaintsFlow = ai.defineFlow(
  {
    name: 'filterFalseComplaintsFlow',
    inputSchema: FilterFalseComplaintsInputSchema,
    outputSchema: FilterFalseComplaintsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
