// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI tool to parse a user's voice command.
 *
 * - parseCommand - A function that interprets a spoken command.
 * - ParseCommandInput - The input type for the parseCommand function.
 * - ParseCommandOutput - The return type for the parseCommand function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ParseCommandInputSchema = z.object({
  commandText: z.string().describe('The transcribed text from the user\'s speech.'),
  language: z.string().describe('The language the user is speaking in (e.g., "en", "hi").'),
});
export type ParseCommandInput = z.infer<typeof ParseCommandInputSchema>;

const ParseCommandOutputSchema = z.object({
    command: z
        .enum(['goToFeed', 'goToReport', 'goToMyReports', 'goToProfile', 'logout', 'changeLanguage', 'unknown'])
        .describe("The command the user wants to execute. If the intent is unclear, return 'unknown'."),
    targetLanguage: z.string().optional().describe("If the command is 'changeLanguage', this should be the language code (e.g., 'hi', 'en', 'bn', 'ur')."),
});
export type ParseCommandOutput = z.infer<typeof ParseCommandOutputSchema>;


const prompt = ai.definePrompt({
  name: 'parseCommandPrompt',
  input: {schema: ParseCommandInputSchema},
  output: {schema: ParseCommandOutputSchema},
  prompt: `You are a voice command interpreter for a civic issue reporting app. Your task is to analyze the user's spoken command and determine their intent.

The user is speaking in language: {{language}}.

The available actions are:
- **goToFeed**: For navigating to the main issue feed. Examples: "show feed", "go home", "main page".
- **goToReport**: For navigating to the page to report a new issue. Examples: "report an issue", "file a complaint", "शिकायत करनी है", "report karna hai".
- **goToMyReports**: For navigating to the page where the user can see their own reported issues. Examples: "show my reports", "meri reports dikhao".
- **goToProfile**: For navigating to the user's profile page. Examples: "show my profile", "profile kholo".
- **logout**: For logging the user out. Examples: "log me out", "sign out".
- **changeLanguage**: For changing the app's display language. You must also determine the target language code. Examples: "translate to hindi", "change language to bengali", "urdu me karo".
  - Supported language codes: en (English), hi (Hindi), bn (Bengali), ur (Urdu).

Analyze the following command and map it to one of the available actions. If the command is to change language, you MUST populate the 'targetLanguage' field with the correct code.

User command: "{{commandText}}"

If the command is ambiguous or does not match any of the intents, classify it as 'unknown'.
Return the result in JSON format.`,
});

const parseCommandFlow = ai.defineFlow(
  {
    name: 'parseCommandFlow',
    inputSchema: ParseCommandInputSchema,
    outputSchema: ParseCommandOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);


export async function parseCommand(
  input: ParseCommandInput
): Promise<ParseCommandOutput> {
  return parseCommandFlow(input);
}
