// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI tool to translate text, with caching.
 *
 * - translateText - A function that translates text, checking a cache first.
 * - TranslateTextInput - The input type for the translateText function.
 * - TranslateTextOutput - The return type for the translateText function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import {createClient} from '@/lib/supabase/server';
import {cookies} from 'next/headers';

const TranslateTextInputSchema = z.object({
  issueId: z.string().describe('The ID of the issue being translated.'),
  text: z.string().describe('The text to be translated.'),
  targetLanguage: z
    .string()
    .describe(
      'The target language to translate the text into (e.g., "hi", "en").'
    ),
});
export type TranslateTextInput = z.infer<typeof TranslateTextInputSchema>;

const TranslateTextOutputSchema = z.object({
  translatedText: z.string().describe('The translated text.'),
});
export type TranslateTextOutput = z.infer<typeof TranslateTextOutputSchema>;

export async function translateText(
  input: TranslateTextInput
): Promise<TranslateTextOutput> {
  return translateTextFlow(input);
}

const prompt = ai.definePrompt({
  name: 'translateTextPrompt',
  input: {
    schema: z.object({
      text: z.string(),
      targetLanguage: z.string(),
    }),
  },
  output: {schema: TranslateTextOutputSchema},
  prompt: `Translate the following text into the language represented by the code '{{targetLanguage}}'. Only return the translated text, with no additional explanation or preamble.

Text to translate:
"{{{text}}}"
`,
});

const translateTextFlow = ai.defineFlow(
  {
    name: 'translateTextFlow',
    inputSchema: TranslateTextInputSchema,
    outputSchema: TranslateTextOutputSchema,
  },
  async ({issueId, text, targetLanguage}) => {
    const cookieStore = cookies();
    const supabase = createClient(cookieStore);

    // 1. Check cache first
    const {data: cachedTranslation} = await supabase
      .from('translations')
      .select('translated_text')
      .eq('issue_id', issueId)
      .eq('language_code', targetLanguage)
      .single();

    if (cachedTranslation) {
      return {translatedText: cachedTranslation.translated_text};
    }

    // 2. If not in cache, translate
    const {output} = await prompt({text, targetLanguage});
    const translatedText = output!.translatedText;

    // 3. Save to cache
    if (translatedText) {
      await supabase.from('translations').insert({
        issue_id: issueId,
        language_code: targetLanguage,
        translated_text: translatedText,
      });
    }

    return {translatedText};
  }
);
